USE [master]
GO

/****** Object:  Database [Bridge]    Script Date: 2/5/2022 12:05:28 AM ******/
CREATE DATABASE [Bridge]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bridge', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Bridge.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Bridge_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Bridge_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Bridge].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Bridge] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Bridge] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Bridge] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Bridge] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Bridge] SET ARITHABORT OFF 
GO

ALTER DATABASE [Bridge] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Bridge] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Bridge] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Bridge] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Bridge] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Bridge] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Bridge] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Bridge] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Bridge] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Bridge] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Bridge] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Bridge] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Bridge] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Bridge] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Bridge] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Bridge] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Bridge] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Bridge] SET RECOVERY FULL 
GO

ALTER DATABASE [Bridge] SET  MULTI_USER 
GO

ALTER DATABASE [Bridge] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Bridge] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Bridge] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Bridge] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Bridge] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Bridge] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Bridge] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Bridge] SET  READ_WRITE 
GO


