//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeDA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BridgeEntities : DbContext
    {
        public BridgeEntities()
            : base("name=BridgeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCategory> tblCategories { get; set; }
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblInventoryOrder> tblInventoryOrders { get; set; }
        public DbSet<tblOrderItem> tblOrderItems { get; set; }
        public DbSet<tblProduct> tblProducts { get; set; }
        public DbSet<tblSupplier> tblSuppliers { get; set; }

        public void SubmitChanges()
        {
            throw new NotImplementedException();
        }
    }
}
